version: "3.8"
services:
  movies:
    # build: ./movies
    build:
      context: ./movies
      dockerfile: Dockerfile
    networks: 
      mongoNetwork: {}
    ports: 
      - "3001:3001"
    container_name: movies-container
    env_file: ./movies/.env
networks:
  mongoNetwork:
    driver: bridge
    name: mongoNetwork